# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "NeuronaLabs"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false

[db.seed]
enabled = true
sql_paths = ['./seed.sql']

[realtime]
enabled = false

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = false

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.image_transformation]
enabled = false

[storage.buckets]
[storage.buckets.dicom]
public = false
file_size_limit = "50MiB"
allowed_mime_types = ["application/dicom"]

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true

[analytics]
enabled = false

[edge_runtime]
enabled = false

[imgproxy]
enabled = false

[vector]
enabled = false

[logflare]
enabled = false
