version: '3.9'

x-common-env: &common-env
  ENVIRONMENT: ${ENVIRONMENT:-production}
  LOG_LEVEL: ${LOG_LEVEL:-Warning}

x-backend-env: &backend-env
  ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
  Supabase__Url: ${NEXT_PUBLIC_SUPABASE_URL}
  Supabase__AnonKey: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
  Supabase__ServiceKey: ${SUPABASE_SERVICE_ROLE_KEY}
  Orthanc__BaseUrl: ${ORTHANC_URL}
  JWT__SecretKey: ${JWT_SECRET}

x-frontend-env: &frontend-env
  NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
  NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://backend}
  NEXT_PUBLIC_OHIF_URL: ${NEXT_PUBLIC_OHIF_URL:-http://ohif-viewer}

services:
  # Backend .NET Core API
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: neuronalabs-backend
    environment:
      <<: [*common-env, *backend-env]
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    depends_on:
      - orthanc
    networks:
      - neuronalabs_network

  orthanc:
    image: jodogne/orthanc-plugins:latest
    container_name: neuronalabs-orthanc
    volumes:
      - orthanc_data:/var/lib/orthanc/db
      - ./dicom_storage:/var/lib/orthanc/dicom
    ports:
      - "${ORTHANC_PORT:-8042}:8042"
    environment:
      - ORTHANC_BASE_URL=${ORTHANC_URL}
    healthcheck:
      test: ["CMD-SHELL", "wget -q http://localhost:8042/system -O - || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - neuronalabs_network

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: neuronalabs-frontend
    environment:
      <<: [*common-env, *frontend-env]
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - backend
    networks:
      - neuronalabs_network

  # OHIF DICOM Viewer
  ohif-viewer:
    image: ohif/viewer
    container_name: neuronalabs-ohif
    environment:
      - REACT_APP_ORTHANC_URL=${ORTHANC_URL}
    ports:
      - "${OHIF_PORT:-3010}:80"
    depends_on:
      - orthanc
    networks:
      - neuronalabs_network

volumes:
  orthanc_data:

networks:
  neuronalabs_network:
    driver: bridge
