global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Sledování .NET Core backend
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:80']

  # Sledování PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Sledování Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Sledování Node Exporteru
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

# Alerting rules
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "/etc/prometheus/alert_rules.yml"
