apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuronalabs-backend
  labels:
    app: neuronalabs-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neuronalabs-backend
  template:
    metadata:
      labels:
        app: neuronalabs-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/neuronalabs/backend:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: connection-string
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 15

---

apiVersion: v1
kind: Service
metadata:
  name: neuronalabs-backend-service
spec:
  selector:
    app: neuronalabs-backend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

---

apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
type: Opaque
stringData:
  connection-string: "Host=postgres;Port=5432;Database=neuronalabs;Username=postgres;Password=postgres"
