-- Vytvoření tabulky patients
CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    date_of_birth DATE NOT NULL,
    gender TEXT NOT NULL,
    last_diagnosis TEXT
);

-- Vytvoření tabulky diagnostic_data
CREATE TABLE diagnostic_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
    diagnosis_type TEXT NOT NULL,
    description TEXT NOT NULL,
    date TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Vytvoření tabulky dicom_studies
CREATE TABLE dicom_studies (
    study_instance_uid TEXT PRIMARY KEY,
    patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
    modality TEXT NOT NULL,
    study_date TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Vytvoření indexů pro zlepšení výkonu
CREATE INDEX idx_diagnostic_data_patient_id ON diagnostic_data(patient_id);
CREATE INDEX idx_dicom_studies_patient_id ON dicom_studies(patient_id);

