name: Kontinuální Integrace

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DOTNET_VERSION: '8.0.x'
  NODE_VERSION: '18.x'

jobs:
  backend-build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Obnovení závislostí
      run: dotnet restore backend/NeuronaLabs.csproj
    
    - name: Build Backend
      run: dotnet build backend/NeuronaLabs.csproj -c Release --no-restore
    
    - name: Spuštění unit testů
      run: dotnet test backend/NeuronaLabs.Tests/NeuronaLabs.Tests.csproj -c Release --no-build
    
    - name: Statická analýza kódu
      uses: dotnet/code-analysis@v1
      with:
        projectPath: backend/NeuronaLabs.csproj

  frontend-build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Instalace závislostí
      run: |
        cd frontend
        npm ci
    
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
    
    - name: Spuštění testů
      run: |
        cd frontend
        npm run test

  docker-build:
    needs: [backend-build-and-test, frontend-build-and-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login do Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build a publikace Backend Docker obrazu
      run: |
        docker build -t neuronalabs-backend:latest -f backend/Dockerfile .
        docker tag neuronalabs-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/neuronalabs-backend:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/neuronalabs-backend:${{ github.sha }}
    
    - name: Build a publikace Frontend Docker obrazu
      run: |
        docker build -t neuronalabs-frontend:latest -f frontend/Dockerfile .
        docker tag neuronalabs-frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/neuronalabs-frontend:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/neuronalabs-frontend:${{ github.sha }}

  security-scan:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Skenování závislostí
      uses: snyk/actions/dotnet@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test
    
    - name: Skenování Docker obrazů
      uses: anchore/scan-action@v3
      with:
        image: "${{ secrets.DOCKERHUB_USERNAME }}/neuronalabs-backend:${{ github.sha }}"
        fail-build: true
        severity-cutoff: high

  deployment:
    needs: [security-scan]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Konfigurace Kubernetes
      uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    
    - name: Nasazení do Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yml
        kubectl set image deployment/neuronalabs-backend backend=${{ secrets.DOCKERHUB_USERNAME }}/neuronalabs-backend:${{ github.sha }}
        kubectl set image deployment/neuronalabs-frontend frontend=${{ secrets.DOCKERHUB_USERNAME }}/neuronalabs-frontend:${{ github.sha }}
        kubectl rollout status deployment/neuronalabs-backend
        kubectl rollout status deployment/neuronalabs-frontend
